name: Build, Test & Deploy Spring App

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deployToUAT:
        description: 'Deploy to UAT (true/false)'
        required: true
        default: 'false'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: ./gradlew test

      - name: Build the application
        run: ./gradlew clean assemble

  deploy-to-qa:
    name: Deploy to QA Environment
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to QA
        run: echo "Deploying to QA environment"
        # Add your actual deployment commands here

  deploy-to-uat:
    name: Deploy to UAT Environment
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deployToUAT == 'true'
    steps:
      - name: Deploy to UAT
        run: echo "Deploying to UAT environment"
        # Add your actual deployment commands here
