name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  learning-yml:
    name: Learning Github Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

